### ISSUE TITLE
More useful and consistent Tick Subscription calls

### ISSUE THREAD

**Issue by borisyankov** [binary-com/websockets#19]
Following functionality is needed to support the scenarios we try to implement:

1. Any call subscribes to a list of ticks (1 or more)
2. Any call auto-unsubscribes from other ticks, instead of adding to the list
3. So I can just subscribe to [] and that means I unsubscribed
4. All responses per tick are into a single response, not multiple
5. Each response does not repeat the epoch, just one epoch and a list of quotes

**Comment by raunakkathuria** [comment]
@borisyankov for point `Any call auto-unsubscribes from other ticks, instead of adding to the list` I don't think we should do that, consider example where we widget like application, we add one widget that subscribe to one underlying, then add another that subscribe to another in this case we should not disable the previous tick

**Comment by borisyankov** [comment]
The widget app has the responsibility of managing its state, it is not the responsibility of the back-end to do that. So even if the app looks like it has separate 'widgets' it has internally the list of the symbols.

With the current API, even if once the app forgets to unsubscribe, we have 'leaked' subscription, that the app does not know about. Remember you had the same bug in Trading page? :)
