### ISSUE TITLE
.NET framework no longer capable of connecting to websockets

### ISSUE THREAD

**Issue by DragonFly81** [binary-com/websockets#45]
As per the forum discussion, one can no longer connect to websockets via .NET without immediately getting a websocket error:   "System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."

Connecting via JavaScript is unaffected by this.  Please treat this as urgent.

**Comment by raunakkathuria** [comment]
does .NET websocket library support TLS1.1 and above? Yesterday we have disabled TLS1.0 due to compliance requirement. That's likely to cause the issue

Try looking for c# port of bouncy castle crypto to see if can use that for ssl/tls handshake in .NET websocket library

checkout https://msdn.microsoft.com/en-us/library/system.security.authentication.sslprotocols(v=vs.110).aspx.aspx) use .NET Framework 4.5 and explicitly set to TLS1.1 or TLS1.2

by default when not set, .NET Framework uses TLS1.0

also .NET framework below 4.5 does not have TLS1.1 and above support

**Comment by borisyankov** [comment]
I'll also check this out, and if this is the fix will update the example.

**Comment by DragonFly81** [comment]
Thanks @raunakkathuria and @borisyankov - I've confirmed that when using the stock .NET Websocket object (as in your online example), one need only add the line:
"System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;"
before initializing an instance of the object in order to get it working.  You may want to add that line into the example with a short comment on ensuring .NET 4.5 or higher is used with SSL and TLS 1.0 ideally disabled in the system registry.
I'm struggling to find a 3rd Party framework where one can specify the transfer protocol (System.Net.WebSockets is horrible to work with) - neither WebSockets4Net nor WebSocketsSharp seem to allow me to specify the transfer protocol, opting only to kick out with "The client and server cannot communicate, because they do not possess a common algorithm".
That's my problem, however, not yours.  Please feel free to close this issue if you're comfortable to do so.

**Comment by borisyankov** [comment]
Example is updated. Thanks.
