### ISSUE TITLE
Candle requests are failing for granularity below 180

### ISSUE THREAD

**Issue by DragonFly81** [binary-com/websockets#56]
@raunakkathuria @jy-binary  I tested this in the Playground as well and it's definitely not working anymore.  Please fix urgently:

    {
      "echo_req": {
        "granularity": "120",
        "count": "40",
        "ticks_history": "frxUSDJPY",
        "subscribe": "1",
        "style": "candles",
        "end": "latest"
      },
      "error": {
        "details": {
          "granularity": "does not have a value in the enumeration {0,60,120,180,300,600,900,1800,3600,7200,14400,28800,86400}"
        },
        "message": "Input validation failed: granularity",
        "code": "InputValidationFailed"
      },
      "msg_type": "ticks_history"
    }

**Comment by raunakkathuria** [comment]
We are checking, will update you accordingly

**Comment by raunakkathuria** [comment]
@DragonFly81 you are passing granularity as string i.e. in double quotes but its of integer type
https://developers.binary.com/api/#ticks_history

```
granularity 0 60 120 180 300 600 900 1800 3600 7200 14400 28800 86400
```

Earlier as there was security issue in code due to type casting so you could use string for integer, we have fixed that please update your code accordingly

**Comment by DragonFly81** [comment]
Thank you
